import os

# 元素名称中英文对照字典
element_names = {
    'Hydrogen': '氢',
    'Helium': '氦',
    'Lithium': '锂',
    'Beryllium': '铍',
    'Boron': '硼',
    'Carbon': '碳',
    'Nitrogen': '氮',
    'Oxygen': '氧',
    'Fluorine': '氟',
    'Neon': '氖',
    'Sodium': '钠',
    'Magnesium': '镁',
    'Aluminum': '铝',
    'Silicon': '硅',
    'Phosphorus': '磷',
    'Sulfur': '硫',
    'Chlorine': '氯',
    'Argon': '氩',
    'Potassium': '钾',
    'Calcium': '钙',
    'Scandium': '钪',
    'Titanium': '钛',
    'Vanadium': '钒',
    'Chromium': '铬',
    'Manganese': '锰',
    'Iron': '铁',
    'Cobalt': '钴',
    'Nickel': '镍',
    'Copper': '铜',
    'Zinc': '锌',
    'Gallium': '镓',
    'Germanium': '锗',
    'Arsenic': '砷',
    'Selenium': '硒',
    'Bromine': '溴',
    'Krypton': '氪',
    'Rubidium': '铷',
    'Strontium': '锶',
    'Yttrium': '钇',
    'Zirconium': '锆',
    'Niobium': '铌',
    'Molybdenum': '钼',
    'Technetium': '锝',
    'Ruthenium': '钌',
    'Rhodium': '铑',
    'Palladium': '钯',
    'Silver': '银',
    'Cadmium': '镉',
    'Indium': '铟',
    'Tin': '锡',
    'Antimony': '锑',
    'Tellurium': '碲',
    'Iodine': '碘',
    'Xenon': '氙',
    'Cesium': '铯',
    'Barium': '钡',
    'Lanthanum': '镧',
    'Cerium': '铈',
    'Praseodymium': '镨',
    'Neodymium': '钕',
    'Promethium': '钷',
    'Samarium': '钐',
    'Europium': '铕',
    'Gadolinium': '钆',
    'Terbium': '铽',
    'Dysprosium': '镝',
    'Holmium': '钬',
    'Erbium': '铒',
    'Thulium': '铥',
    'Ytterbium': '镱',
    'Lutetium': '镥',
    'Hafnium': '铪',
    'Tantalum': '钽',
    'Tungsten': '钨',
    'Rhenium': '铼',
    'Osmium': '锇',
    'Iridium': '铱',
    'Platinum': '铂',
    'Gold': '金',
    'Mercury': '汞',
    'Thallium': '铊',
    'Lead': '铅',
    'Bismuth': '铋',
    'Polonium': '钋',
    'Astatine': '砹',
    'Radon': '氡',
    'Francium': '钫',
    'Radium': '镭',
    'Actinium': '锕',
    'Thorium': '钍',
    'Protactinium': '镤',
    'Uranium': '铀',
    'Neptunium': '镎',
    'Plutonium': '钚',
    'Americium': '镅',
    'Curium': '锔',
    'Berkelium': '锫',
    'Californium': '锎',
    'Einsteinium': '锿',
    'Fermium': '镄',
    'Mendelevium': '钔',
    'Nobelium': '锘',
    'Lawrencium': '铹',
    'Rutherfordium': '𬬻',
    'Dubnium': '𬭊',
    'Seaborgium': '𬭳',
    'Bohrium': '𬭛',
    'Hassium': '𬭶',
    'Meitnerium': '鿏',
    'Darmstadtium': '𫟼',
    'Roentgenium': '𬬭',
    'Copernicium': '鿔',
    'Nihonium': '鿭',
    'Flerovium': '𫓧',
    'Moscovium': '镆',
    'Livermorium': '𫟷',
    'Tennessine': '鿬',
    'Oganesson': '鿫'
}

# 元素名称到元素符号的映射字典
element_symbols = {
    'Hydrogen': 'H',
    'Helium': 'He',
    'Lithium': 'Li',
    'Beryllium': 'Be',
    'Boron': 'B',
    'Carbon': 'C',
    'Nitrogen': 'N',
    'Oxygen': 'O',
    'Fluorine': 'F',
    'Neon': 'Ne',
    'Sodium': 'Na',
    'Magnesium': 'Mg',
    'Aluminum': 'Al',
    'Silicon': 'Si',
    'Phosphorus': 'P',
    'Sulfur': 'S',
    'Chlorine': 'Cl',
    'Argon': 'Ar',
    'Potassium': 'K',
    'Calcium': 'Ca',
    'Scandium': 'Sc',
    'Titanium': 'Ti',
    'Vanadium': 'V',
    'Chromium': 'Cr',
    'Manganese': 'Mn',
    'Iron': 'Fe',
    'Cobalt': 'Co',
    'Nickel': 'Ni',
    'Copper': 'Cu',
    'Zinc': 'Zn',
    'Gallium': 'Ga',
    'Germanium': 'Ge',
    'Arsenic': 'As',
    'Selenium': 'Se',
    'Bromine': 'Br',
    'Krypton': 'Kr',
    'Rubidium': 'Rb',
    'Strontium': 'Sr',
    'Yttrium': 'Y',
    'Zirconium': 'Zr',
    'Niobium': 'Nb',
    'Molybdenum': 'Mo',
    'Technetium': 'Tc',
    'Ruthenium': 'Ru',
    'Rhodium': 'Rh',
    'Palladium': 'Pd',
    'Silver': 'Ag',
    'Cadmium': 'Cd',
    'Indium': 'In',
    'Tin': 'Sn',
    'Antimony': 'Sb',
    'Tellurium': 'Te',
    'Iodine': 'I',
    'Xenon': 'Xe',
    'Cesium': 'Cs',
    'Barium': 'Ba',
    'Lanthanum': 'La',
    'Cerium': 'Ce',
    'Praseodymium': 'Pr',
    'Neodymium': 'Nd',
    'Promethium': 'Pm',
    'Samarium': 'Sm',
    'Europium': 'Eu',
    'Gadolinium': 'Gd',
    'Terbium': 'Tb',
    'Dysprosium': 'Dy',
    'Holmium': 'Ho',
    'Erbium': 'Er',
    'Thulium': 'Tm',
    'Ytterbium': 'Yb',
    'Lutetium': 'Lu',
    'Hafnium': 'Hf',
    'Tantalum': 'Ta',
    'Tungsten': 'W',
    'Rhenium': 'Re',
    'Osmium': 'Os',
    'Iridium': 'Ir',
    'Platinum': 'Pt',
    'Gold': 'Au',
    'Mercury': 'Hg',
    'Thallium': 'Tl',
    'Lead': 'Pb',
    'Bismuth': 'Bi',
    'Polonium': 'Po',
    'Astatine': 'At',
    'Radon': 'Rn',
    'Francium': 'Fr',
    'Radium': 'Ra',
    'Actinium': 'Ac',
    'Thorium': 'Th',
    'Protactinium': 'Pa',
    'Uranium': 'U',
    'Neptunium': 'Np',
    'Plutonium': 'Pu',
    'Americium': 'Am',
    'Curium': 'Cm',
    'Berkelium': 'Bk',
    'Californium': 'Cf',
    'Einsteinium': 'Es',
    'Fermium': 'Fm',
    'Mendelevium': 'Md',
    'Nobelium': 'No',
    'Lawrencium': 'Lr',
    'Rutherfordium': 'Rf',
    'Dubnium': 'Db',
    'Seaborgium': 'Sg',
    'Bohrium': 'Bh',
    'Hassium': 'Hs',
    'Meitnerium': 'Mt',
    'Darmstadtium': 'Ds',
    'Roentgenium': 'Rg',
    'Copernicium': 'Cn',
    'Nihonium': 'Nh',
    'Flerovium': 'Fl',
    'Moscovium': 'Mc',
    'Livermorium': 'Lv',
    'Tennessine': 'Ts',
    'Oganesson': 'Og'
}

# 读取english目录下的文件名，获取元素编号和名称
def get_elements():
    elements = []
    english_dir = 'english'
    for filename in os.listdir(english_dir):
        if filename.endswith('.html'):
            match = re.match(r'^(\d+)_(.*?)\.html$', filename)
            if match:
                number = match.group(1).zfill(2)  # 确保两位数
                element_name = match.group(2)
                elements.append((number, element_name))
    # 按元素编号排序
    elements.sort(key=lambda x: int(x[0]))
    return elements

def generate_element_links():
    elements = get_elements()
    element_links = []
    for number, element_name in elements:
        chinese_name = element_names.get(element_name, element_name)
        element_symbol = element_symbols.get(element_name, '')
        if element_symbol:
            link = f'            <a href="chinese/{number}{element_symbol}.html" class="element-link">\n                <span>{chinese_name}</span>\n            </a>'
            element_links.append(link)
    return '\n'.join(element_links)

# 更新chinese.html文件
def update_chinese_html():
    with open('chinese.html', 'r', encoding='utf-8') as f:
        content = f.read()
    
    element_links = generate_element_links()
    
    # 替换元素链接部分
    updated_content = re.sub(r'(<div class="element-grid">)(.*?)(</div>)', 
                           r'\1\n' + element_links + r'\n\3', 
                           content, 
                           flags=re.DOTALL)
    
    with open('chinese.html', 'w', encoding='utf-8') as f:
        f.write(updated_content)

if __name__ == '__main__':
    import re
    update_chinese_html()
    print('已更新chinese.html文件，添加了所有元素的链接！')